/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Diaz_TP7.vista;

import Diaz_TP7.entidad.Alumno;
import Diaz_TP7.entidad.Materia;
import java.awt.event.KeyEvent;
import java.util.HashSet;
import javax.swing.JOptionPane;

/**
 *
 * @author long_
 */
public class viewFormularioDeInscripcion extends javax.swing.JInternalFrame {
    HashSet<Alumno> listaDeAlumnos;
    HashSet<Materia> listaDeMaterias;
    /**
     * Creates new form viewFormularioDeInscripcion
     * @param listaDeAlumnos
     * @param listaDeMaterias
     */
    public viewFormularioDeInscripcion(HashSet<Alumno> listaDeAlumnos, HashSet<Materia> listaDeMaterias) {
        initComponents();
        this.listaDeAlumnos = listaDeAlumnos;
        this.listaDeMaterias = listaDeMaterias;
        llenarComboAlumnos();
        llenarComboMaterias();
        this.requestFocus();
    }

    public void mensaje(String mensaje){
        JOptionPane.showMessageDialog(this, mensaje);
    }
    
    public void agregarMateriaAlAlumno(){
        try{
            Alumno a = (Alumno) jcbElijaUnAlumno.getSelectedItem();
            Materia m = (Materia) jcbElijaUnaMateria.getSelectedItem();
            a.agregarMateria(m);
        }catch(NullPointerException npe){
            mensaje("La lista de alumnos o la de materias esta vacia, por favor agregue por lo menos una materia y un alumno para inscribirlo en dicha materia.");
        }
    }
    
    public void llenarComboAlumnos(){
        for(Alumno a: listaDeAlumnos){
            jcbElijaUnAlumno.addItem(a);
        }
    }
    
    public void llenarComboMaterias(){
        for(Materia m: listaDeMaterias){
            jcbElijaUnaMateria.addItem(m);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlFormularioDeInscripcion = new javax.swing.JLabel();
        jlElijaUnaMateria = new javax.swing.JLabel();
        jlElijaUnAlumno = new javax.swing.JLabel();
        jcbElijaUnaMateria = new javax.swing.JComboBox<>();
        jcbElijaUnAlumno = new javax.swing.JComboBox<>();
        jbSalir = new javax.swing.JButton();
        jbInscribir = new javax.swing.JButton();

        setTitle("Formulario de Inscripción");

        jlFormularioDeInscripcion.setText("Formulario de Inscripción");

        jlElijaUnaMateria.setText("Elija una materia:");

        jlElijaUnAlumno.setText("Elija un alumno:");

        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });
        jbSalir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbSalirKeyPressed(evt);
            }
        });

        jbInscribir.setText("Inscribir");
        jbInscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbInscribirActionPerformed(evt);
            }
        });
        jbInscribir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbInscribirKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbInscribir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbSalir))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlElijaUnaMateria)
                            .addComponent(jlElijaUnAlumno))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlFormularioDeInscripcion)
                            .addComponent(jcbElijaUnaMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbElijaUnAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jlFormularioDeInscripcion)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlElijaUnaMateria)
                    .addComponent(jcbElijaUnaMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlElijaUnAlumno)
                    .addComponent(jcbElijaUnAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSalir)
                    .addComponent(jbInscribir))
                .addContainerGap())
        );

        setBounds(80, 80, 396, 189);
    }// </editor-fold>//GEN-END:initComponents

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        dispose();
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jbInscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbInscribirActionPerformed
        agregarMateriaAlAlumno();
    }//GEN-LAST:event_jbInscribirActionPerformed

    private void jbInscribirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbInscribirKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            agregarMateriaAlAlumno();
        }
    }//GEN-LAST:event_jbInscribirKeyPressed

    private void jbSalirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbSalirKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            dispose();
        }
    }//GEN-LAST:event_jbSalirKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbInscribir;
    private javax.swing.JButton jbSalir;
    private javax.swing.JComboBox<Alumno> jcbElijaUnAlumno;
    private javax.swing.JComboBox<Materia> jcbElijaUnaMateria;
    private javax.swing.JLabel jlElijaUnAlumno;
    private javax.swing.JLabel jlElijaUnaMateria;
    private javax.swing.JLabel jlFormularioDeInscripcion;
    // End of variables declaration//GEN-END:variables
}
