/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Diaz_TP7.vista;

import Diaz_TP7.entidad.Alumno;
import java.awt.event.KeyEvent;

import java.util.HashSet;
import javax.swing.JOptionPane;

/**
 *
 * @author long_
 */
public class viewFormularioDeAlumnos extends javax.swing.JInternalFrame {
    HashSet<Alumno> listaDeAlumnos;
    /**
     * Creates new form viewFormularioDeAlumnos
     * @param listaDeAlumnos
     */
    public viewFormularioDeAlumnos(HashSet<Alumno>listaDeAlumnos) {
        initComponents();
        this.listaDeAlumnos = listaDeAlumnos;
        this.requestFocus();
        jtfNumeroDeLegajo.requestFocus();
    }
    
    public void mensaje(String mensaje){
        JOptionPane.showMessageDialog(this,mensaje);
    }
    
    public void limpiar(){
        jtfNumeroDeLegajo.setText("");
        jtfNombre.setText("");
        jtfApellido.setText("");
    }
    
    public void agregarAlumno(){
        int numeroDeLegajo = Integer.parseInt(jtfNumeroDeLegajo.getText());
        Alumno alumno = new Alumno(numeroDeLegajo, jtfNombre.getText(), jtfApellido.getText());
        if(listaDeAlumnos.isEmpty()){
            listaDeAlumnos.add(alumno);
            limpiar();
            mensaje("Alumno agregado correctamente.");
            jtfNumeroDeLegajo.requestFocus();
        } else {
            boolean agregar = listaDeAlumnos.add(alumno);
            if(agregar){
                listaDeAlumnos.add(alumno);
                mensaje("Alumno agregado correctamente.");
                limpiar();
                jtfNumeroDeLegajo.requestFocus();
            } else {
                mensaje("El alumno ya se encuentra ingresado.");
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbSalir = new javax.swing.JButton();
        jbNuevo = new javax.swing.JButton();
        jbGuardar = new javax.swing.JButton();
        jlFormularioDeAlumnos = new javax.swing.JLabel();
        jlNumeroDeLegajo = new javax.swing.JLabel();
        jlApellido = new javax.swing.JLabel();
        jllNombre = new javax.swing.JLabel();
        jtfNumeroDeLegajo = new javax.swing.JTextField();
        jtfApellido = new javax.swing.JTextField();
        jtfNombre = new javax.swing.JTextField();

        setTitle("Formulario de alumnos");

        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });
        jbSalir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbSalirKeyPressed(evt);
            }
        });

        jbNuevo.setText("Nuevo");
        jbNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevoActionPerformed(evt);
            }
        });
        jbNuevo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbNuevoKeyPressed(evt);
            }
        });

        jbGuardar.setText("Guardar");
        jbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarActionPerformed(evt);
            }
        });
        jbGuardar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbGuardarKeyPressed(evt);
            }
        });

        jlFormularioDeAlumnos.setText("Formulario de Alumnos");

        jlNumeroDeLegajo.setText("Número de legajo:");

        jlApellido.setText("Apellido:");

        jllNombre.setText("Nombre:");

        jtfNumeroDeLegajo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfNumeroDeLegajoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfNumeroDeLegajoKeyTyped(evt);
            }
        });

        jtfApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfApellidoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfApellidoKeyTyped(evt);
            }
        });

        jtfNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfNombreKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfNombreKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 136, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jbGuardar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbNuevo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbSalir)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jlFormularioDeAlumnos)
                                .addGap(125, 125, 125))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlNumeroDeLegajo)
                            .addComponent(jlApellido)
                            .addComponent(jllNombre))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfNombre)
                            .addComponent(jtfApellido)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtfNumeroDeLegajo, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jlFormularioDeAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNumeroDeLegajo)
                    .addComponent(jtfNumeroDeLegajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlApellido)
                    .addComponent(jtfApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jllNombre)
                    .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSalir)
                    .addComponent(jbNuevo)
                    .addComponent(jbGuardar))
                .addContainerGap())
        );

        setBounds(80, 80, 400, 232);
    }// </editor-fold>//GEN-END:initComponents

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        dispose();
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jbNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevoActionPerformed
        limpiar();
    }//GEN-LAST:event_jbNuevoActionPerformed

    private void jbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarActionPerformed
        if (jtfNumeroDeLegajo.getText().trim().length() == 0 || jtfNombre.getText().trim().length() == 0 || jtfApellido.getText().trim().length() == 0) {
                mensaje("Faltan rellenar campos.");
            } else {
                agregarAlumno();
            }
    }//GEN-LAST:event_jbGuardarActionPerformed

    private void jtfNumeroDeLegajoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNumeroDeLegajoKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c)) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jtfNumeroDeLegajoKeyTyped

    private void jtfApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfApellidoKeyTyped
        
    }//GEN-LAST:event_jtfApellidoKeyTyped

    private void jtfNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNombreKeyTyped
        
    }//GEN-LAST:event_jtfNombreKeyTyped

    private void jtfNumeroDeLegajoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNumeroDeLegajoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (jtfNumeroDeLegajo.getText().trim().length() == 0 || jtfNombre.getText().trim().length() == 0 || jtfApellido.getText().trim().length() == 0) {
                mensaje("Faltan rellenar campos.");
            } else {
                agregarAlumno();
            }
        }
    }//GEN-LAST:event_jtfNumeroDeLegajoKeyPressed

    private void jtfApellidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfApellidoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (jtfNumeroDeLegajo.getText().trim().length() == 0 || jtfNombre.getText().trim().length() == 0 || jtfApellido.getText().trim().length() == 0) {
                mensaje("Faltan rellenar campos.");
            } else {
                agregarAlumno();
            }
        }
    }//GEN-LAST:event_jtfApellidoKeyPressed

    private void jtfNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNombreKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (jtfNumeroDeLegajo.getText().trim().length() == 0 || jtfNombre.getText().trim().length() == 0 || jtfApellido.getText().trim().length() == 0) {
                mensaje("Faltan rellenar campos.");
            } else {
                agregarAlumno();
            }
        }
    }//GEN-LAST:event_jtfNombreKeyPressed

    private void jbGuardarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbGuardarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (jtfNumeroDeLegajo.getText().trim().length() == 0 || jtfNombre.getText().trim().length() == 0 || jtfApellido.getText().trim().length() == 0) {
                mensaje("Faltan rellenar campos.");
            } else {
                agregarAlumno();
            }
        }
    }//GEN-LAST:event_jbGuardarKeyPressed

    private void jbNuevoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbNuevoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            limpiar();
        }
    }//GEN-LAST:event_jbNuevoKeyPressed

    private void jbSalirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbSalirKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            dispose();
        }
    }//GEN-LAST:event_jbSalirKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbGuardar;
    private javax.swing.JButton jbNuevo;
    private javax.swing.JButton jbSalir;
    private javax.swing.JLabel jlApellido;
    private javax.swing.JLabel jlFormularioDeAlumnos;
    private javax.swing.JLabel jlNumeroDeLegajo;
    private javax.swing.JLabel jllNombre;
    private javax.swing.JTextField jtfApellido;
    private javax.swing.JTextField jtfNombre;
    private javax.swing.JTextField jtfNumeroDeLegajo;
    // End of variables declaration//GEN-END:variables
}
