/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Diaz_TP7.vista;

import Diaz_TP7.entidad.Materia;
import java.awt.event.KeyEvent;
import java.util.HashSet;
import javax.swing.JOptionPane;

/**
 *
 * @author long_
 */
public class viewFormularioDeMaterias extends javax.swing.JInternalFrame {
    HashSet<Materia> listaDeMaterias;
    /**
     * Creates new form viewFormularioDeMaterias
     * @param listaDeMaterias
     */
    public viewFormularioDeMaterias(HashSet<Materia>listaDeMaterias) {
        initComponents();
        this.listaDeMaterias = listaDeMaterias;
        this.requestFocus();
        jtfCodigoDeMateria.requestFocus();
    }
    
    public void mensaje(String mensaje){
        JOptionPane.showMessageDialog(this,mensaje);
    }

    public void agregarMateria(){
        int codigoDeMateria = Integer.parseInt(jtfCodigoDeMateria.getText());
        int añoAlQuePertenece = Integer.parseInt(jtfAñoAlQuePertenece.getText());
        Materia materia = new Materia(codigoDeMateria, jtfNombreDeLaMateria.getText(), añoAlQuePertenece);
        if(listaDeMaterias.isEmpty()){
                listaDeMaterias.add(materia);
                mensaje("Materia registrada correctamente.");
                limpiar();
            } else {
            boolean agregar = listaDeMaterias.add(materia);
                if(agregar){
                    listaDeMaterias.add(materia);
                    mensaje("Materia registrada correctamente.");
                    limpiar();
                } else {
                    mensaje("La materia ya se encuentra registrada.");
                }
            }
    }
    
    public void limpiar(){
        jtfCodigoDeMateria.setText("");
        jtfNombreDeLaMateria.setText("");
        jtfAñoAlQuePertenece.setText("");
        jtfCodigoDeMateria.requestFocus();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlCodigoDeMateria = new javax.swing.JLabel();
        jlFormularioDeMaterias = new javax.swing.JLabel();
        jlNombreDeLaMateria = new javax.swing.JLabel();
        jlAñoAlQuePertenece = new javax.swing.JLabel();
        jtfNombreDeLaMateria = new javax.swing.JTextField();
        jtfAñoAlQuePertenece = new javax.swing.JTextField();
        jtfCodigoDeMateria = new javax.swing.JTextField();
        jbSalir = new javax.swing.JButton();
        jbGuardar = new javax.swing.JButton();
        jbNuevo = new javax.swing.JButton();

        jlCodigoDeMateria.setText("Código de materia:");

        jlFormularioDeMaterias.setText("Formulario de Materias");

        jlNombreDeLaMateria.setText("Nombre de la materia:");

        jlAñoAlQuePertenece.setText("Año al que pertenece:");

        jtfNombreDeLaMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNombreDeLaMateriaActionPerformed(evt);
            }
        });
        jtfNombreDeLaMateria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfNombreDeLaMateriaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfNombreDeLaMateriaKeyTyped(evt);
            }
        });

        jtfAñoAlQuePertenece.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfAñoAlQuePerteneceKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfAñoAlQuePerteneceKeyTyped(evt);
            }
        });

        jtfCodigoDeMateria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfCodigoDeMateriaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfCodigoDeMateriaKeyTyped(evt);
            }
        });

        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });
        jbSalir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbSalirKeyPressed(evt);
            }
        });

        jbGuardar.setText("Guardar");
        jbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarActionPerformed(evt);
            }
        });
        jbGuardar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbGuardarKeyPressed(evt);
            }
        });

        jbNuevo.setText("Nuevo");
        jbNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevoActionPerformed(evt);
            }
        });
        jbNuevo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbNuevoKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlNombreDeLaMateria)
                            .addComponent(jlCodigoDeMateria)
                            .addComponent(jlAñoAlQuePertenece))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfAñoAlQuePertenece)
                            .addComponent(jtfNombreDeLaMateria)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtfCodigoDeMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbNuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbSalir)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jlFormularioDeMaterias)
                .addContainerGap(138, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jlFormularioDeMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCodigoDeMateria)
                    .addComponent(jtfCodigoDeMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNombreDeLaMateria)
                    .addComponent(jtfNombreDeLaMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlAñoAlQuePertenece)
                    .addComponent(jtfAñoAlQuePertenece, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSalir)
                    .addComponent(jbGuardar)
                    .addComponent(jbNuevo))
                .addContainerGap())
        );

        setBounds(80, 80, 400, 235);
    }// </editor-fold>//GEN-END:initComponents

    private void jtfNombreDeLaMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNombreDeLaMateriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNombreDeLaMateriaActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        dispose();
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jbNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevoActionPerformed
        
    }//GEN-LAST:event_jbNuevoActionPerformed

    private void jbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarActionPerformed
        if (jtfCodigoDeMateria.getText().trim().length() == 0 || jtfNombreDeLaMateria.getText().trim().length() == 0 || jtfAñoAlQuePertenece.getText().trim().length() == 0) {
            mensaje("Faltan rellenar campos.");
        } else {
            agregarMateria();
        }
    }//GEN-LAST:event_jbGuardarActionPerformed

    private void jtfCodigoDeMateriaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCodigoDeMateriaKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c)) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jtfCodigoDeMateriaKeyTyped

    private void jtfAñoAlQuePerteneceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfAñoAlQuePerteneceKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c)) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();
        }
        String Caracteres = jtfAñoAlQuePertenece.getText();
        if (Caracteres.length() >= 2) {
            evt.consume();
        }
    }//GEN-LAST:event_jtfAñoAlQuePerteneceKeyTyped

    private void jbGuardarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbGuardarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (jtfCodigoDeMateria.getText().trim().length() == 0 || jtfNombreDeLaMateria.getText().trim().length() == 0 || jtfAñoAlQuePertenece.getText().trim().length() == 0) {
                mensaje("Faltan rellenar campos.");
            } else {
                agregarMateria();
            }
        }
    }//GEN-LAST:event_jbGuardarKeyPressed

    private void jbNuevoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbNuevoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            limpiar();
        }
    }//GEN-LAST:event_jbNuevoKeyPressed

    private void jtfCodigoDeMateriaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCodigoDeMateriaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (jtfCodigoDeMateria.getText().trim().length() == 0 || jtfNombreDeLaMateria.getText().trim().length() == 0 || jtfAñoAlQuePertenece.getText().trim().length() == 0) {
                mensaje("Faltan rellenar campos.");
            } else {
                agregarMateria();
            }
        }
    }//GEN-LAST:event_jtfCodigoDeMateriaKeyPressed

    private void jtfNombreDeLaMateriaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNombreDeLaMateriaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (jtfCodigoDeMateria.getText().trim().length() == 0 || jtfNombreDeLaMateria.getText().trim().length() == 0 || jtfAñoAlQuePertenece.getText().trim().length() == 0) {
                mensaje("Faltan rellenar campos.");
            } else {
                agregarMateria();
            }
        }
    }//GEN-LAST:event_jtfNombreDeLaMateriaKeyPressed

    private void jtfNombreDeLaMateriaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNombreDeLaMateriaKeyTyped
        
    }//GEN-LAST:event_jtfNombreDeLaMateriaKeyTyped

    private void jtfAñoAlQuePerteneceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfAñoAlQuePerteneceKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (jtfCodigoDeMateria.getText().trim().length() == 0 || jtfNombreDeLaMateria.getText().trim().length() == 0 || jtfAñoAlQuePertenece.getText().trim().length() == 0) {
                mensaje("Faltan rellenar campos.");
            } else {
                agregarMateria();
            }
        }
    }//GEN-LAST:event_jtfAñoAlQuePerteneceKeyPressed

    private void jbSalirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbSalirKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            dispose();
        }
    }//GEN-LAST:event_jbSalirKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbGuardar;
    private javax.swing.JButton jbNuevo;
    private javax.swing.JButton jbSalir;
    private javax.swing.JLabel jlAñoAlQuePertenece;
    private javax.swing.JLabel jlCodigoDeMateria;
    private javax.swing.JLabel jlFormularioDeMaterias;
    private javax.swing.JLabel jlNombreDeLaMateria;
    private javax.swing.JTextField jtfAñoAlQuePertenece;
    private javax.swing.JTextField jtfCodigoDeMateria;
    private javax.swing.JTextField jtfNombreDeLaMateria;
    // End of variables declaration//GEN-END:variables
}
