/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Diaz_TP7.vista;

import Diaz_TP7.entidad.Materia;
import java.util.HashSet;
import javax.swing.JOptionPane;

/**
 *
 * @author long_
 */
public class viewFormularioDeMaterias extends javax.swing.JInternalFrame {
    HashSet<Materia> listaDeMaterias;
    /**
     * Creates new form viewFormularioDeMaterias
     * @param listaDeMaterias
     */
    public viewFormularioDeMaterias(HashSet<Materia>listaDeMaterias) {
        initComponents();
        this.listaDeMaterias = listaDeMaterias;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlCodigoDeMateria = new javax.swing.JLabel();
        jlFormularioDeMaterias = new javax.swing.JLabel();
        jlNombreDeLaMateria = new javax.swing.JLabel();
        jlAñoAlQuePertenece = new javax.swing.JLabel();
        jtfNombreDeLaMateria = new javax.swing.JTextField();
        jtfAñoAlQuePertenece = new javax.swing.JTextField();
        jtfCodigoDeMateria = new javax.swing.JTextField();
        jbSalir = new javax.swing.JButton();
        jbGuardar = new javax.swing.JButton();
        jbNuevo = new javax.swing.JButton();

        jlCodigoDeMateria.setText("Código de materia:");

        jlFormularioDeMaterias.setText("Formulario de Materias");

        jlNombreDeLaMateria.setText("Nombre de la materia:");

        jlAñoAlQuePertenece.setText("Año al que pertenece:");

        jtfNombreDeLaMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNombreDeLaMateriaActionPerformed(evt);
            }
        });

        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        jbGuardar.setText("Guardar");
        jbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarActionPerformed(evt);
            }
        });

        jbNuevo.setText("Nuevo");
        jbNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlNombreDeLaMateria)
                            .addComponent(jlCodigoDeMateria)
                            .addComponent(jlAñoAlQuePertenece))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfAñoAlQuePertenece)
                            .addComponent(jtfNombreDeLaMateria)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtfCodigoDeMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbNuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbSalir)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jlFormularioDeMaterias)
                .addContainerGap(138, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jlFormularioDeMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCodigoDeMateria)
                    .addComponent(jtfCodigoDeMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNombreDeLaMateria)
                    .addComponent(jtfNombreDeLaMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlAñoAlQuePertenece)
                    .addComponent(jtfAñoAlQuePertenece, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSalir)
                    .addComponent(jbGuardar)
                    .addComponent(jbNuevo))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfNombreDeLaMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNombreDeLaMateriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNombreDeLaMateriaActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        dispose();
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jbNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevoActionPerformed
        jtfCodigoDeMateria.setText("");
        jtfNombreDeLaMateria.setText("");
        jtfAñoAlQuePertenece.setText("");
    }//GEN-LAST:event_jbNuevoActionPerformed

    private void jbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarActionPerformed
        try{
            int codigoDeMateria = Integer.parseInt(jtfCodigoDeMateria.getText());
            int añoAlQuePertenece = Integer.parseInt(jtfAñoAlQuePertenece.getText());
            Materia materia = new Materia(codigoDeMateria, jtfNombreDeLaMateria.getText(), añoAlQuePertenece);
            if(listaDeMaterias.isEmpty()){
                listaDeMaterias.add(materia);
                jtfCodigoDeMateria.setText("");
                jtfNombreDeLaMateria.setText("");
                jtfAñoAlQuePertenece.setText("");
                JOptionPane.showMessageDialog(this,"Materia registrada correctamente.");
            } else {
            boolean agregar = listaDeMaterias.add(materia);
                if(agregar){
                    listaDeMaterias.add(materia);
                    jtfCodigoDeMateria.setText("");
                    jtfNombreDeLaMateria.setText("");
                    jtfAñoAlQuePertenece.setText("");
                    JOptionPane.showMessageDialog(this,"Materia registrada correctamente.");
                } else {
                    JOptionPane.showMessageDialog(this,"La materia ya se encuentra registrada.");
                    jtfCodigoDeMateria.setText("");
                    jtfNombreDeLaMateria.setText("");
                    jtfAñoAlQuePertenece.setText("");
                }
            }
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this,"Código o año incorrecto.");
        }
    }//GEN-LAST:event_jbGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbGuardar;
    private javax.swing.JButton jbNuevo;
    private javax.swing.JButton jbSalir;
    private javax.swing.JLabel jlAñoAlQuePertenece;
    private javax.swing.JLabel jlCodigoDeMateria;
    private javax.swing.JLabel jlFormularioDeMaterias;
    private javax.swing.JLabel jlNombreDeLaMateria;
    private javax.swing.JTextField jtfAñoAlQuePertenece;
    private javax.swing.JTextField jtfCodigoDeMateria;
    private javax.swing.JTextField jtfNombreDeLaMateria;
    // End of variables declaration//GEN-END:variables
}
